name: CI

on: [push]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ["14.x", "16.x", "17.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --network-timeout 1000000

      - name: Lint
        run: yarn lint:fix

      - name: Pretty
        run: yarn pretty:fix

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Cache Coverage
        id: cache-coverage
        uses: actions/cache@v3
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage

      - name: Upload coverage to Coveralls
        if: steps.cache-coverage.outputs.cache-hit == 'true'
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        if: steps.cache-coverage.outputs.cache-hit == 'true'
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          verbose: true

      - name: Build
        run: yarn build

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --network-timeout 1000000

      - name: Lint
        run: yarn lint:fix

      - name: Pretty
        run: yarn pretty:fix

      - name: Build
        run: yarn build

      - name: Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.SEMANTIC_RELEASE_GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SEMANTIC_RELEASE_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SEMANTIC_RELEASE_GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SEMANTIC_RELEASE_GIT_EMAIL }}
